Add unit test for config limit on Gen2
With the current implementation, this test fails with:

```
AssertionError: Tuples differ: (0, 1, 2, 3, 4, 5) != (1, 2, 4)

First differing element 0:
0
1

First tuple contains 3 additional elements.
First extra element 3:
3

- (0, 1, 2, 3, 4, 5)
+ (1, 2, 4)
```

Joints 0, 3 and 5 are unbounded in the Gen2 description, thus should be
ignored by configuration limits.