Switch to ProxQP in triple-task convergence test
Using DAQP in this test resulted in:

    ERROR: test_three_tasks_convergence (tests.test_solve_ik.TestSolveIK.test_three_tasks_convergence)
    Three simultaneously feasible tasks on the JVRC model converge.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/frankd/src/pink/tests/test_solve_ik.py", line 307, in test_three_tasks_convergence
        velocity = solve_ik(configuration, tasks, dt, solver="daqp")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/frankd/src/pink/pink/solve_ik.py", line 209, in solve_ik
        configuration.check_limits(safety_break=safety_break)
      File "/home/frankd/src/pink/pink/configuration.py", line 187, in check_limits
        raise NotWithinConfigurationLimits(
    pink.exceptions.NotWithinConfigurationLimits: Joint 16 violates configuration limits 0.0 <= -0.011322782431648803 <= 2.61799387799